#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H
/*
options: 1-ENABLED 
         2-DISABLED
*/
#define EXTI_u8_INT0_Control  ENABLED

/*
options: 1-ENABLED 
         2-DISABLED
*/
#define EXTI_u8_INT1_Control  ENABLED

/*
options: 1-ENABLED 
         2-DISABLED
*/
#define EXTI_u8_INT2_Control  ENABLED

/*
OPTIONS: 1-LOW_LEVEL 
         2-ON_CHANGE
		 3-FALLING_EDGE
		 4-RISING_EDGE
*/
#define EXTI_u8_INT0_SENSE FALLING_EDGE

/*
OPTIONS: 1-LOW_LEVEL 
         2-ON_CHANGE
		 3-FALLING_EDGE
		 4-RISING_EDGE
*/
#define EXTI_u8_INT1_SENSE FALLING_EDGE

/*
OPTIONS: 1-LOW_LEVEL 
         2-ON_CHANGE
		 3-FALLING_EDGE
		 4-RISING_EDGE
*/
#define EXTI_u8_INT2_SENSE FALLING_EDGE

#endif


